# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
     app.admin.terrain:
            class: WCS\CoavBundle\Admin\TerrainAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Content", label: "Terrain" }
            arguments:
                - ~
                - WCS\CoavBundle\Entity\Terrain
                - ~